apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice
  labels:
    app: msa-banking-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: customer-service
      app: msa-banking-app

  template:
    metadata:
      name: customer-msa-pod
      labels:
        name: customer-service
        app: msa-banking-app
    spec:
      containers:
      - name: customer-container
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 600m
            memory: 700Mi

      imagePullSecrets:
          - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
  labels:
    name: customer-service
    app: msa-banking-app

spec:
  type: ClusterIP
  ports:
  -  protocol: TCP
     targetPort: 3256
     port: 3256

  selector:
    name: customer-service
    app: msa-banking-app