server:
  port: 3256
  
spring:
  application:
    name: customerservice
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://microservices-eureka-service:8761/eureka/
  instance:
     hostname: customerservice
